plugins:
  - jekyll-seo-tag

author: Determination
Social: Armaan.I/Mashuq.I
links: https://iigaxer.github.io/Profile/

title: M.I's Profile

description: This is a profile, everything you need to know about Armaan/Mahshuq!
