plugins:
  - jekyll-seo-tag

author: Determination
Social: Armaan/Mahshuq
links: https://iigaxer.github.io/PROJECT-HTML/

title: Mashuq's Profile

description: This is a profile, everything you need to know about Armaan/Mahshuq!
